export const FEEDBACK_CATEGORIES = ["Code Quality", "System Design", "Testing", "UI / UX", "Security"];
export const FEEDBACK_STATUSES = ["Action Required", "In Review", "Resolved"];

export const INITIAL_FEEDBACK = [
  {
    id: "FB-1048",
    title: "Dashboard UI Implementation",
    project: "Intern Dashboard",
    category: "Code Quality",
    mentor: "Rahul Patil",
    role: "Frontend Mentor",
    rating: 4.8,
    status: "Resolved",
    date: "Aug 29, 2026",
    summary: "Strong component structure with clean responsive implementation.",
    strengths: [
      "Good use of reusable React components.",
      "Responsive layouts are consistent across screen sizes.",
      "Tailwind utility classes are organized clearly.",
    ],
    improvements: [
      "Consider extracting repeated spacing patterns.",
      "Add a few more empty and loading states.",
    ],
  },
  {
    id: "FB-1045",
    title: "API Integration",
    project: "Intern Dashboard",
    category: "System Design",
    mentor: "Ananya Sharma",
    role: "Backend Mentor",
    rating: 4.5,
    status: "In Review",
    date: "Aug 28, 2026",
    summary: "API integration is working well with appropriate loading and error handling.",
    strengths: ["Endpoints are integrated correctly.", "Error states have been handled cleanly."],
    improvements: [
      "Improve API error messages shown to users.",
      "Consider creating a reusable API service layer.",
    ],
  },
  {
    id: "FB-1042",
    title: "Login & Registration UI",
    project: "Authentication Module",
    category: "UI / UX",
    mentor: "Priya Sharma",
    role: "UI/UX Mentor",
    rating: 4.2,
    status: "Action Required",
    date: "Aug 26, 2026",
    summary: "The authentication flow is complete, but mobile spacing and validation states need refinement.",
    strengths: ["Clean visual hierarchy.", "Password visibility interaction is implemented well."],
    improvements: [
      "Improve spacing on smaller screens.",
      "Add clearer validation feedback for form fields.",
      "Review keyboard navigation and accessibility states.",
    ],
  },
  {
    id: "FB-1039",
    title: "Project Documentation",
    project: "Intern Dashboard",
    category: "Code Quality",
    mentor: "Rahul Patil",
    role: "Frontend Mentor",
    rating: 4.9,
    status: "Resolved",
    date: "Aug 24, 2026",
    summary: "Clear documentation with useful setup and development instructions.",
    strengths: ["Project setup is easy to understand.", "Component documentation is concise and useful."],
    improvements: ["Add a short troubleshooting section."],
  },
  {
    id: "FB-1035",
    title: "Testing & Validation",
    project: "Task Module",
    category: "Testing",
    mentor: "Ananya Sharma",
    role: "Technical Mentor",
    rating: 4.7,
    status: "Resolved",
    date: "Aug 22, 2026",
    summary: "Good validation coverage with a few opportunities for additional edge-case testing.",
    strengths: ["Core user flows are covered.", "Validation behavior is predictable."],
    improvements: ["Add more edge-case tests.", "Include negative API response scenarios."],
  },
];

export const MENTORS = [
  { value: "Rahul Patil", label: "Rahul Patil — Frontend Mentor" },
  { value: "Ananya Sharma", label: "Ananya Sharma — Backend Mentor" },
  { value: "Priya Sharma", label: "Priya Sharma — UI/UX Mentor" },
];
